arquivo = open("teste.txt")
# print(arquivo)
# print(arquivo.name)
# print(arquivo.mode)
# print(arquivo.closed)
print(arquivo.read())
palavras_do_arquivo = arquivo.seek(0)
print(palavras_do_arquivo)
# print(palavras_do_arquivo)